### ISSUE TITLE
irrelevant genes

### ISSUE THREAD

**Issue by adebali** [adebali/repairrepo#4]
![image](https://user-images.githubusercontent.com/3449123/48715286-b934f200-ec25-11e8-98e5-cc7d4e26261e.png)

`Adora1` is not in the range but it is listed.

**Comment by yash1376** [comment]
updated the push script and updated the db. Working on fixing the Stitch app error where the script returns nothing upon querying

**Comment by yash1376** [comment]
still in the works, the name query is working now but the chr region is still causing errors due to size limits of mongodb. Support is helping me out on solutions
